title: 桂电1024
description: 非官方桂电开源社区，收录优秀项目和有价值的学习资料。
head: 
  - - link
    - { rel: 'icon', href: '/assets/img/guet1024.png' }
base: /
host: 0.0.0.0
port: 8778
  
themeConfig: 
  logo: '/assets/img/guet1024.png'
  nav:
    - {text: '主页', link: '/' }
    - {text: '文章', link: '/article/' }
    - {text: 'GitHub', link: 'https://github.com/guet1024' }
    
  
