# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.15.1]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run a one-line script
        run: echo Build GUET1024 Homepage!

      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn docs:build

      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0 
        with:  
          username: 'root'
          #server: '${{secrets.NOWORLD_IP}}'
          #ssh_private_key: ${{secrets.NOWORLD_SSH_PRIVATE_KEY}} 

          server: '117.50.105.172'
          ssh_private_key: n,O.W/orld 
          local_path: './docs/.vuepress/dist/*' 
          remote_path: '/www/wwwroot/guet1024.cn'
          args: '-o ConnectTimeout=5'